Layout/CommentIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lamba:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
